version: '3'

services:
  bitcoin-native:
    image: quay.io/quarkus/quarkus-micro-image:1.0
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql-bitcoin:3306/bitcoin_negotiation?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
    networks:
      - mysql-db   
    ports:
      - 8080:8080
    depends_on:
      - mysql-bitcoin

  mysql-bitcoin: 
    image: aluracursos/mysql-quarkus-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.bitcoin:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-db

networks:
 mysql-db:
  driver: bridge

volumes:
  mysql.bitcoin: